Enhance SimpleToastWidget with Close Button
payam-zahedi/toastification pull request #151
Opened 2024-10-17 21:18 UTC by AntonioAEMartins

**Key Features:**

1. Close Button Support:

The SimpleToastWidget now includes a close button that can be configured using the showCloseButton argument. This allows the widget to:

- Always show the close button.

- Hide the close button.

- Support custom behaviors where the close button can be conditionally rendered (e.g., when integrated with styles that provide hover behavior).

2. Customizable Close Button Behavior:

By utilizing the ToastificationStyle, users can decide if the SimpleToastWidget should:

- Show a permanent close button.

- Omit the close button entirely.

- Customize for advanced behaviors (like on hover, if implemented externally).

close #106

2024-10-17 21:25 UTC, AntonioAEMartins commented
Hi @payam-zahedi,

I hope you're doing well. As per our discussion on issue #106, I’ve implemented the close button functionality for the SimpleToastWidget. I’ve tested it using the Toastification WebApp Page, and everything is functioning smoothly.

One area I wanted to highlight is related to the onHover button type. I aimed to implement an animation for this case to handle the expansion of the widget when the button appears on hover. Initially, I faced a challenge where, if the button space is pre-allocated, the text isn’t centered properly. On the other hand, if I don’t pre-allocate the space, the toast expands when hovered.

Please let me know if there are any changes or improvements you'd suggest. I’m open to refining it further based on your recommendations.

2024-10-28 07:23 UTC, payam-zahedi commented
Hey @AntonioAEMartins 

Thanks for your contribution

regarding on hover and toast allocated space I should try it to see what is the best practice 

I will check it and let you know

2024-10-28 07:43 UTC, payam-zahedi commented on lib/src/widget/built_in/built_in_builder.dart
>              ),
You need to  pass `onCloseTap` parameter as well

2024-10-28 07:45 UTC, payam-zahedi commented on lib/src/widget/built_in/simple/simple.dart
> +  _SimpleToastWidgetState createState() => _SimpleToastWidgetState();
We don't need to make this widget as Statefull we don't have any state in this widget

2024-10-28 07:53 UTC, payam-zahedi requested changes

2024-10-28 07:53 UTC, payam-zahedi commented on lib/src/widget/built_in/simple/simple.dart
> +    with SingleTickerProviderStateMixin {
We don't need SingleTickerProviderStateMixin we only use this class when we want to use AnimationController so please remove it

2024-10-28 07:53 UTC, payam-zahedi commented on lib/src/widget/built_in/simple/simple.dart
> +  final bool? showCloseButton;
Make this parameter non-nullable 

We alwase send a boolean value to the widget

2024-10-28 07:53 UTC, payam-zahedi commented on lib/src/widget/built_in/simple/simple.dart
> +          Expanded(
If you want to have a widget which allocate size only base on its content you can use Flexible widget 

Check out this example:

``` dart 

    Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Flexible(
          fit: FlexFit.loose,
          child: widget.title ?? const SizedBox(),
        ),
        ToastCloseButton(
          showCloseButton: showCloseButton,
          onCloseTap: widget.onCloseTap,
          icon: widget.defaultStyle.closeIcon(context),
          iconColor: widget.foregroundColor?.withOpacity(.3) ??
              widget.defaultStyle.closeIconColor(context),
        ),
      ],
    )
```

2024-10-28 07:53 UTC, payam-zahedi commented on lib/src/widget/built_in/simple/simple.dart
> +    } else {
We don't need this else here becase `ToastCloseButton` will handle its own visibility

2024-10-28 13:53 UTC, AntonioAEMartins reviewed
@payam-zahedi Thank you so much for your valuable feedback! I’ve implemented all the suggested changes, and now I believe the `simple.dart` file aligns more closely with the overall coding style of the other classes within Toastification.

One additional modification I made was adding a conditional check for `if(showCloseButton)` in the following section:

```dart
Row(
  mainAxisSize: MainAxisSize.min,
  children: [
    Flexible(
      fit: FlexFit.loose,
      child: title ?? const SizedBox(),
    ),
    if (showCloseButton) ...[
      const SizedBox(width: 8),
      ToastCloseButton(
        showCloseButton: showCloseButton,
        onCloseTap: onCloseTap,
        icon: defaultStyle.closeIcon(context),
        iconColor: foregroundColor?.withOpacity(.3) ??
            defaultStyle.closeIconColor(context),
      ),
    ]
  ],
);
```

This conditional ensures that when the `ToastCloseButton` is not displayed, it doesn’t take up unnecessary space, allowing for consistent padding on both the left and right sides of the toast.

Looking forward to your thoughts on these changes!

2024-10-28 15:34 UTC, payam-zahedi commented
Thank you, @AntonioAEMartins, for your contributions!

Your changes look solid, and I appreciate the work you put in. If it’s alright with you, I’d like to make a few adjustments to further refine the on-hover close button feature. I believe these tweaks could enhance its functionality and user experience even further.

Let me know if you have any thoughts on this approach!

2024-10-28 18:35 UTC, AntonioAEMartins commented
Great to hear @payam-zahedi 

What are the changes that you have in mind?

2024-10-29 09:25 UTC, payam-zahedi commented
Currently, the behavior of the close button on hover is somewhat inconsistent. It would improve the user experience if we could add a subtle fade-in/out effect along with a slight shrink in size on hover. This would make the interaction smoother and more visually appealing.

2024-10-29 09:29 UTC, payam-zahedi commented
Checkout this video, it seems like the close button’s behavior on appearance and disappearance is a bit abrupt. Adding a smooth fade-in/out animation would enhance the user experience and make the transitions feel more natural.


I do belive we need to add some changes to the CloseButton to make it happend

https://github.com/user-attachments/assets/5d26e5f1-b5b5-4c12-9917-39f71c158caa

2024-10-30 16:37 UTC, payam-zahedi commented
This behavior would be a nice improvement!

https://github.com/user-attachments/assets/405eb2d2-ffc1-4710-a0ae-0c0f0290a0d6

I’d suggest achieving it by updating the CloseButton widget, so the change will apply to other Toasts as well. Using an `AnimatedSwitcher` widget could be a good way to implement it.

Here’s a quick example:



``` dart 
import 'package:flutter/material.dart';

/// Flutter code sample for [AnimatedSwitcher].

void main() => runApp(const AnimatedSwitcherExampleApp());

class AnimatedSwitcherExampleApp extends StatelessWidget {
  const AnimatedSwitcherExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: AnimatedSwitcherExample(),
    );
  }
}

class AnimatedSwitcherExample extends StatefulWidget {
  const AnimatedSwitcherExample({super.key});

  @override
  State<AnimatedSwitcherExample> createState() =>
      _AnimatedSwitcherExampleState();
}

class _AnimatedSwitcherExampleState extends State<AnimatedSwitcherExample> {
  bool show = true;

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: Colors.white,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Container(
            padding: EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.blue[100],
              borderRadius: BorderRadius.circular(8),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text('Some Text'),
                AnimatedSwitcher(
                  duration: const Duration(milliseconds: 500),
                  transitionBuilder:
                      (Widget child, Animation<double> animation) {
                    return FadeTransition(
                      opacity: animation,
                      child: SizeTransition(
                        sizeFactor: animation,
                        axis: Axis.horizontal,
                        child: child,
                      ),
                    );
                  },
                  child: show
                      ? Container(
                          key: ValueKey(1),
                          padding: const EdgeInsets.all(8),
                          decoration: BoxDecoration(
                            color: Colors.red[200],
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Icon(Icons.close),
                        )
                      : SizedBox.shrink(key: ValueKey(2)),
                ),
              ],
            ),
          ),
          ElevatedButton(
            child: const Text('Increment'),
            onPressed: () {
              setState(() {
                show = !show;
              });
            },
          ),
        ],
      ),
    );
  }
}

```

2024-10-30 17:17 UTC, AntonioAEMartins commented
Hi @payam-zahedi,

I’ve made some adjustments to the behavior of the Simple Toast Type based on the example code you provided. Overall, the behavior seems correct, but I noticed a slightly odd (though acceptable) behavior when the Simple Toast has multiple lines of text.

Another issue arises in the "Toast Style Selection" menu, where the Simple Toast is occupying all the available vertical space. There are two potential solutions:

<img width="650" alt="Screenshot 2024-10-30 at 14 12 50" src="https://github.com/user-attachments/assets/60793ca8-e96e-41e7-9504-f5fdfd18544a">

The first is to use a Column, but this approach results in incorrect height behavior. When the user hovers over the Toast, the text slightly shifts downward.

The second solution, which resolves the issue entirely, is to use IntrinsicHeight. However, I’m aware that IntrinsicHeight is known to be computationally expensive.

<img width="641" alt="Screenshot 2024-10-30 at 14 14 16" src="https://github.com/user-attachments/assets/aa7860ad-987d-43ed-b931-5922e8031c7f">

(With IntrinsicHeight)

Do you have any suggestions on how to best address this behavior?

2024-11-02 11:18 UTC, payam-zahedi commented
Hi @AntonioAEMartins,

I reviewed your code and made some adjustments to address the issue you encountered. You can see these changes in my latest commit.

Please take a look and let me know if it aligns with your expectations.

2024-11-03 17:23 UTC, AntonioAEMartins commented
@payam-zahedi I reviewed the changes, and I really liked the animations and overall behavior. The adjustments align perfectly with what I was hoping for.

2024-11-03 19:44 UTC, payam-zahedi commented
@AntonioAEMartins Awesome 

So I will try to resolve conflicts and Merge This PR

2024-11-03 20:47 UTC, payam-zahedi approved these changes
It looks like this PR is now complete.

Thank you very much for your dedication and valuable contributions, @AntonioAEMartins!

2024-11-03 20:47 UTC, merged